### ISSUE TITLE
Rule function-no-unknown crashes after upgrading stylelint to 14.5.0

### ISSUE THREAD

**Issue by crystalfp** [stylelint-scss/stylelint-scss#590]
I'm linting Vue files using stylelint and `postcss-html` (see below). After upgrading stylelint to 14.5.0 from 14.4.0, it started crashing this way:
```
$ npx stylelint ./src/App.vue ./src/components/*.vue ./src/styles/*.scss ./src/styles/*.css

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\stylelint\lib\rules\function-no-unknown\index.js:48:39
    at D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\stylelint\lib\lintPostcssResult.js:113:8
    at Array.map (<anonymous>)
    at lintPostcssResult (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\stylelint\lib\lintPostcssResult.js:104:18)
    at lintSource (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\stylelint\lib\lintSource.js:91:8)
    at async D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\stylelint\lib\standalone.js:227:27
    at async Promise.all (index 0)
    at async standalone (D:\Projects\VUEIdeaIgniterEnvironment\client\node_modules\stylelint\lib\standalone.js:266:22)
```
Everything was working before the upgrade. Now the only solution is to disable the rule.
The stylelint configuration starts this way:
```
extends:
  - stylelint-config-standard-vue
  - stylelint-config-recommended-vue/scss

plugins:
  - stylelint-scss

customSyntax: postcss-html
```
Thanks for any help!
mario

**Comment by crystalfp** [comment]
Seems fixed in [stylelint@14.5.1](https://github.com/stylelint/stylelint/releases/tag/14.5.1).
Closing the issue. Thanks!
